name = "smile-photo-selector-api"
main = "src/index.ts"
compatibility_date = "2026-08-19"
workers_dev = true

[vars]
APP_ENV = "development"
APP_VERSION = "0.1.0"
CORS_ORIGIN = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "smile-photo-selector-dev"
database_id = "e08d4779-8841-4fc3-a80b-58706bed942a"
migrations_dir = "../../migrations"
